### ISSUE TITLE
Traceback displayed on info message in the CTK stdout

### ISSUE THREAD

**Issue by dmartin35** [chaosiq/chaosiq-cloud#56]
When failing to publish an experiment, the CTK logs to stdout a nice "Failed to publish the experiment" message, but also an ugly traceback that shall not be shown to the enduser, imho.

```
[2020-02-25 14:04:34 INFO] Failed to publish the experiment
    Traceback (most recent call last):
      File "/Users/dmartin/.pyenv/versions/3.7.4/envs/chaostk/lib/python3.7/site-packages/urllib3/connection.py", line 157, in _new_conn
        (self._dns_host, self.port), self.timeout, **extra_kw
      File "/Users/dmartin/.pyenv/versions/3.7.4/envs/chaostk/lib/python3.7/site-packages/urllib3/util/connection.py", line 84, in create_connection
        raise err
      File "/Users/dmartin/.pyenv/versions/3.7.4/envs/chaostk/lib/python3.7/site-packages/urllib3/util/connection.py", line 74, in create_connection
        sock.connect(sa)
    ConnectionRefusedError: [Errno 61] Connection refused
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/dmartin/.pyenv/versions/3.7.4/envs/chaostk/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
        chunked=chunked,
      File "/Users/dmartin/.pyenv/versions/3.7.4/envs/chaostk/lib/python3.7/site-packages/urllib3/connectionpool.py", line 376, in _make_request
        self._validate_conn(conn)
      File "/Users/dmartin/.pyenv/versions/3.7.4/envs/chaostk/lib/python3.7/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
        conn.connect()
      File "/Users/dmartin/.pyenv/versions/3.7.4/envs/chaostk/lib/python3.7/site-packages/urllib3/connection.py", line 334, in connect
        conn = self._new_conn()
      File "/Users/dmartin/.pyenv/versions/3.7.4/envs/chaostk/lib/python3.7/site-packages/urllib3/connection.py", line 169, in _new_conn
        self, "Failed to establish a new connection: %s" % e
    urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x1100a4fd0>: Failed to establish a new connection: [Errno 61] Connection refused
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/dmartin/.pyenv/versions/3.7.4/envs/chaostk/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
        timeout=timeout
      File "/Users/dmartin/.pyenv/versions/3.7.4/envs/chaostk/lib/python3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
        method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
      File "/Users/dmartin/.pyenv/versions/3.7.4/envs/chaostk/lib/python3.7/site-packages/urllib3/util/retry.py", line 436, in increment
        raise MaxRetryError(_pool, url, error or ResponseError(cause))
    urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='console.localhost', port=8443): Max retries exceeded with url: /api/v1/organizations/7f3244e9-1ad2-4f76-bd7b-8d2c2bfbad9c/teams/ea85f989-7d2f-4a39-a57f-9ed3b005de81/experiments (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x1100a4fd0>: Failed to establish a new connection: [Errno 61] Connection refused'))
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/dmartin/Sources/chaosiq/chaosiq-cloud/chaoscloud/api/experiment.py", line 24, in publish_experiment
        "experiment": experiment
      File "/Users/dmartin/.pyenv/versions/3.7.4/envs/chaostk/lib/python3.7/site-packages/requests/sessions.py", line 581, in post
        return self.request('POST', url, data=data, json=json, **kwargs)
      File "/Users/dmartin/.pyenv/versions/3.7.4/envs/chaostk/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
        resp = self.send(prep, **send_kwargs)
      File "/Users/dmartin/.pyenv/versions/3.7.4/envs/chaostk/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
        r = adapter.send(request, **kwargs)
      File "/Users/dmartin/.pyenv/versions/3.7.4/envs/chaostk/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
        raise ConnectionError(e, request=request)
    requests.exceptions.ConnectionError: HTTPSConnectionPool(host='console.localhost', port=8443): Max retries exceeded with url: /api/v1/organizations/7f3244e9-1ad2-4f76-bd7b-8d2c2bfbad9c/teams/ea85f989-7d2f-4a39-a57f-9ed3b005de81/experiments (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x1100a4fd0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[2020-02-25 14:04:34 INFO] Starting verification measurement every 2 seconds

```

I would suggest to do, two things:
- increase the log level to error, as it is an error not being able to publish
- removes the traceback from the logger.info and maybe log the exception in the logger.debug

**Comment by dmartin35** [comment]
@Lawouach @russmiles what are your thoughts on that, please ?

**Comment by dmartin35** [comment]
should I add this to the changelog or do we want to keep this internally ?

**Comment by Lawouach** [comment]
Changelog entry is always appreciated :)
